# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9aa440174d8a26c48e49d2203a03eed84eab269345e9e424a89cb74097f57ad8164306c079bbf05eaa4f7d5b4b3ca64d2b3e3ef8fca16e5c66a88b2c708c405

test:
  secret_key_base: 7ebb1e486ffadc4ae1378532e9a57daef66234f85baa20a4640d3078bb646362ee29fde15c3620536aadb50c31296bb76aba06de41b630f8f2fa862aee8ee209

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
